### ISSUE TITLE
Windows [OpenEXR codec is disabled]

### ISSUE THREAD

**Issue by matbeedotcom** [transpchan/Live3D-v2#8]
character sheet: ['double_ponytail_images\\I1.png', 'double_ponytail_images\\I2.png', 'double_ponytail_images\\I3.png', 'double_ponytail_images\\I4.png']
---
test images:  688
---
  0%|                                                                       | 0/688 [00:00<?, ?it/s][ WARN:0@1.630] global grfmt_exr.cpp:102 cv::initOpenEXR imgcodecs: OpenEXR codec is disabled. You can enable it via 'OPENCV_IO_ENABLE_OPENEXR' option. Refer for details and cautions here: https://github.com/opencv/opencv/issues/21326
Traceback (most recent call last):
  File "C:\Users\mail\dev\Live3D\train.py", line 229, in <module>
    test()
  File "C:\Users\mail\dev\Live3D\train.py", line 86, in test
    infer(args, humanflowmodel, image_names_list)
  File "C:\Users\mail\dev\Live3D\train.py", line 114, in infer
    for i, data in enumerate(train_data):
  File "C:\Users\mail\dev\Live3D\python\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "C:\Users\mail\dev\Live3D\python\lib\site-packages\torch\utils\data\dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\mail\dev\Live3D\python\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\mail\dev\Live3D\python\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\mail\dev\Live3D\data_loader.py", line 266, in __getitem__
    target = self.get_gt_from_disk(
  File "C:\Users\mail\dev\Live3D\data_loader.py", line 209, in get_gt_from_disk
    label_np = cv2.cvtColor(cv2.imdecode(np.frombuffer(bio.read(
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\grfmt_exr.cpp:103: error: (-213:The function/feature is not implemented) imgcodecs: OpenEXR codec is disabled. You can enable it via 'OPENCV_IO_ENABLE_OPENEXR' option. Refer for details and cautions here: https://github.com/opencv/opencv/issues/21326 in function 'cv::initOpenEXR'

**Comment by matbeedotcom** [comment]
Fixed via modification of webui.py
```import gradio as gr
import os
import sys
import shutil
from pathlib import Path
import subprocess
os.environ["OPENCV_IO_ENABLE_OPENEXR"]="1"
```

**Comment by transpchan** [comment]
Hi thank you for reporting the bug! Could you Pull Rrequest this?

**Comment by matbeedotcom** [comment]
I see you got to it already!
